# -*- coding: utf-8 -*-
"""Paw Care Pet Studio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3gs3BlAyPVBGwg0YA_3cKTJfVCRyCuJ
"""

"""
Paw Care Pet Studio - 宠物沙龙预约系统
无 Firebase 版本，使用 st.session_state 内存存储（适合演示/测试）
包含 5 个页面、预约表单、模拟数据存储。
"""

import streamlit as st
import datetime
import random
import re

# -------------------------------
# 1. 页面配置
# -------------------------------
st.set_page_config(
    page_title="Paw Care Pet Studio",
    page_icon="🐾",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -------------------------------
# 2. 初始化 session_state 存储
# -------------------------------
if "bookings" not in st.session_state:
    st.session_state.bookings = []   # 存储所有预约记录

# -------------------------------
# 3. 全局样式
# -------------------------------
def inject_css():
    st.markdown("""
    <style>
    * {
        font-family: 'Inter', sans-serif;
    }
    h1, h2, h3, h4, h5 {
        font-family: 'Playfair Display', serif;
    }
    .dark-theme {
        background-color: #1A1A1A;
        color: #f0ece6;
        padding: 2rem 1.5rem;
        border-radius: 12px;
    }
    .dark-theme .card {
        background: rgba(255,255,255,0.06);
        border: 1px solid #915D38;
        border-radius: 12px;
        padding: 1.5rem;
        margin: 0.5rem 0;
    }
    .light-theme {
        background-color: #F8F4ED;
        color: #1A1A1A;
        padding: 2rem 1.5rem;
        border-radius: 12px;
    }
    .light-theme .card-white {
        background: white;
        border-radius: 12px;
        padding: 1rem;
        box-shadow: 0 4px 12px rgba(0,0,0,0.05);
        border: 1px solid #e0d8d0;
    }
    .warning-box {
        background-color: rgba(200, 50, 50, 0.15);
        border-left: 4px solid #d44;
        border-radius: 8px;
        padding: 1rem 1.5rem;
        color: #f0d0d0;
        margin: 1.5rem 0;
    }
    .warning-box strong {
        color: #ff8888;
    }
    .info-box {
        background-color: rgba(255,255,255,0.05);
        border-radius: 8px;
        padding: 1rem 1.5rem;
        border: 1px solid #555;
        margin: 1rem 0;
    }
    .stButton > button {
        background-color: #D48F48;
        color: #1A1A1A;
        font-weight: 600;
        border-radius: 50px;
        border: none;
        padding: 0.5rem 2rem;
    }
    .stButton > button:hover {
        background-color: #c07a3a;
        color: #1A1A1A;
    }
    </style>
    """, unsafe_allow_html=True)

inject_css()

# -------------------------------
# 4. 全局数据
# -------------------------------
PACKAGES = {
    "Basic wash and dry": "basic",
    "Light styling": "light",
    "Full styling": "full"
}

DOG_PRICES = [
    {"range": "0–2kg", "basic": 40, "light": 60, "full": 85},
    {"range": "2–5kg", "basic": 55, "light": 80, "full": 110},
    {"range": "5–10kg", "basic": 70, "light": 100, "full": 135},
    {"range": "10–18kg", "basic": 90, "light": 125, "full": 165},
    {"range": "18–28kg", "basic": 110, "light": 150, "full": 195},
    {"range": "28–40kg", "basic": 130, "light": 175, "full": 225},
    {"range": "40kg+", "basic": 160, "light": 210, "full": 270},
]

CAT_PRICES = [
    {"range": "0–3kg", "short": {"basic": 45, "light": 65, "full": 90}, "long": {"basic": 55, "light": 80, "full": 110}},
    {"range": "3–6kg", "short": {"basic": 60, "light": 85, "full": 115}, "long": {"basic": 70, "light": 100, "full": 135}},
    {"range": "6kg+", "short": {"basic": 80, "light": 110, "full": 145}, "long": {"basic": 95, "light": 130, "full": 170}},
]

BUNDLE_ADDONS = [
    {"id": "dematt", "name": "深层开结护理", "price": 15},
    {"id": "ear", "name": "基础耳道清洁", "price": 12},
    {"id": "nail", "name": "基础指甲修剪", "price": 10},
    {"id": "spa", "name": "基础顺毛SPA", "price": 18},
]

STANDALONE_ADDONS = [
    {"id": "teeth", "name": "专业洁牙", "price": 35},
    {"id": "polish", "name": "美甲抛光", "price": 22},
    {"id": "flea", "name": "驱虫药浴", "price": 30},
    {"id": "aroma", "name": "舒缓精油SPA", "price": 28},
    {"id": "color", "name": "局部造型染色", "price": 45},
]

TIME_SLOTS = [
    "9:00", "9:30", "10:00", "10:30", "11:00", "11:30",
    "12:00", "12:30", "13:00", "13:30", "14:00", "14:30",
    "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"
]

GROOMERS = ["Emma (Senior)", "James (Stylist)", "Lily (Cat Specialist)", "Marcus (Breed Expert)"]
PET_TYPES = ["Dog", "Cat"]
DOG_BREEDS = ["Golden Retriever", "Labrador", "Poodle", "Bulldog", "Beagle", "German Shepherd", "Other"]
CAT_BREEDS = ["Persian", "Maine Coon", "Siamese", "British Shorthair", "Ragdoll", "Other"]

# -------------------------------
# 5. 辅助函数（替代 Firebase）
# -------------------------------
def get_package_price(pet_type, weight_range, package_key, coat_type="short"):
    if pet_type == "Dog":
        for row in DOG_PRICES:
            if row["range"] == weight_range:
                return row.get(package_key, 0)
    else:
        for row in CAT_PRICES:
            if row["range"] == weight_range:
                coat = "long" if coat_type == "long" else "short"
                return row[coat].get(package_key, 0)
    return 0

def calculate_total(pet_type, weight_range, package_key, coat_type, selected_bundles, selected_standalone):
    base = get_package_price(pet_type, weight_range, package_key, coat_type)
    bundle_total = sum(item["price"] for item in BUNDLE_ADDONS if item["id"] in selected_bundles)
    standalone_total = sum(item["price"] for item in STANDALONE_ADDONS if item["id"] in selected_standalone)
    return base + bundle_total + standalone_total

def get_booked_slots(date_str):
    """从 session_state 中查询该日期已被占用的时段"""
    booked = []
    for b in st.session_state.bookings:
        if b.get("date") == date_str:
            booked.append(b.get("time"))
    # 为演示效果，随机模拟一些占用（仅当无真实数据时）
    if not booked and len(st.session_state.bookings) < 3:
        # 固定种子，使每次运行一致
        random.seed(date_str + "seed")
        booked = random.sample(TIME_SLOTS, k=random.randint(1, 3))
    return booked

def save_booking(booking_data):
    """将预约记录存入 session_state"""
    booking_id = f"B{len(st.session_state.bookings)+1:04d}"
    booking_data["id"] = booking_id
    st.session_state.bookings.append(booking_data)
    st.success(f"✅ 预约已提交！订单号：{booking_id}")
    st.json(booking_data)
    return booking_id

# -------------------------------
# 6. 页面函数（与之前相同，仅替换存储函数）
# -------------------------------
def page_home():
    with st.container():
        st.markdown('<div class="dark-theme">', unsafe_allow_html=True)
        col1, col2 = st.columns([2, 1])
        with col1:
            st.markdown("""
            # Luxury Grooming
            ## for Your Best Friend
            """)
            st.markdown("Paw Care Pet Studio offers premium wash, styling, and wellness services in a calm, spa-like environment.")
            if st.button("Book Now", key="home_book"):
                st.session_state.page = "Services"
                st.experimental_rerun()
        with col2:
            st.image("https://via.placeholder.com/400x300/2a1f18/915D38?text=Studio+Image", use_column_width=True)
        st.markdown("---")
        st.markdown("## Why Paw Care")
        cols = st.columns(3)
        with cols[0]:
            st.markdown("""
            <div class="card">
                <h3>🧴 SPA Experience</h3>
                <p>Hydro-massage, aromatherapy, and soothing music for a truly relaxing groom.</p>
            </div>
            """, unsafe_allow_html=True)
        with cols[1]:
            st.markdown("""
            <div class="card">
                <h3>✂️ Expert Stylists</h3>
                <p>Certified groomers with years of experience in breed-specific styling.</p>
            </div>
            """, unsafe_allow_html=True)
        with cols[2]:
            st.markdown("""
            <div class="card">
                <h3>❤️ Safe & Gentle</h3>
                <p>Hypoallergenic products, gentle handling, and a calm environment for every pet.</p>
            </div>
            """, unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

def page_about():
    with st.container():
        st.markdown('<div class="dark-theme">', unsafe_allow_html=True)
        st.markdown("## About Paw Care")
        st.markdown("A sanctuary for pets in the heart of Liverpool, Sydney.")
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("""
            Founded in 2020, Paw Care Pet Studio was born from a simple belief: every pet deserves a grooming experience that feels like a spa day.
            We combine premium products, skilled hands, and a deep love for animals.
            """)
            st.metric("Happy Pets", "500+")
            st.metric("Average Rating", "4.9 ★")
        with col2:
            st.image("https://via.placeholder.com/400x300/2a1f18/915D38?text=Studio+Interior", use_column_width=True)
            st.markdown("""
            **128 Park St, Liverpool NSW 2170**
            Mon – Sat 9:00 – 18:00 · Closed Sunday
            📞 +61 2 9600 8899
            """)
        st.markdown("---")
        st.markdown("### Our Grooming Team")
        team = st.columns(4)
        for i, name in enumerate(GROOMERS):
            with team[i]:
                st.image(f"https://via.placeholder.com/100x100/3a3a3a/915D38?text={name[:1]}", width=100)
                st.caption(name)
        st.markdown('</div>', unsafe_allow_html=True)

def page_services():
    with st.container():
        st.markdown('<div class="dark-theme">', unsafe_allow_html=True)
        st.markdown("## Our Services")
        st.markdown("Choose from three care packages, plus add-ons. All prices are per pet and include a full consultation.")

        col1, col2, col3 = st.columns(3)
        with col1:
            st.markdown("""
            <div class="card" style="text-align:center;">
                <h3>Basic wash and dry</h3>
                <p>Gentle bath, blow-dry, and brush-out.</p>
                <p style="color:#D48F48;">from $40</p>
            </div>
            """, unsafe_allow_html=True)
        with col2:
            st.markdown("""
            <div class="card" style="text-align:center; border-color:#D48F48;">
                <h3>Light styling</h3>
                <p>Wash + light trim and shaping.</p>
                <p style="color:#D48F48;">from $60</p>
            </div>
            """, unsafe_allow_html=True)
        with col3:
            st.markdown("""
            <div class="card" style="text-align:center;">
                <h3>Full styling</h3>
                <p>Complete groom + detailed styling & finish.</p>
                <p style="color:#D48F48;">from $85</p>
            </div>
            """, unsafe_allow_html=True)

        with st.expander("🐕 Dog Grooming Prices"):
            dog_data = []
            for row in DOG_PRICES:
                dog_data.append([row["range"], f"${row['basic']}", f"${row['light']}", f"${row['full']}"])
            st.table(dog_data)

        with st.expander("🐈 Cat Grooming Prices"):
            cat_data = []
            for row in CAT_PRICES:
                cat_data.append([row["range"], f"${row['short']['basic']} / ${row['long']['basic']}",
                                 f"${row['short']['light']} / ${row['long']['light']}",
                                 f"${row['short']['full']} / ${row['long']['full']}"])
            st.table(cat_data)

        # ---------- 预约表单 ----------
        st.markdown("---")
        st.markdown("## Book Now")
        st.markdown("Fill in the details below to secure your pet's spot.")

        if "booking_step" not in st.session_state:
            st.session_state.booking_step = 1

        if st.session_state.booking_step == 1:
            st.subheader("Step 1: Verify Your Mobile")
            phone = st.text_input("Mobile Number", placeholder="+61 4XX XXX XXX", key="phone_input")
            if st.button("Send Verification Code"):
                if re.match(r'^\+61\d{9,10}$', phone.replace(" ", "")):
                    st.session_state.phone = phone
                    st.session_state.booking_step = 2
                    st.success("Code sent (demo: 123456)")
                    st.experimental_rerun()
                else:
                    st.error("Please enter a valid Australian mobile number (e.g., +61 412345678)")

        elif st.session_state.booking_step == 2:
            st.subheader("Step 2: Choose Service Details")
            col1, col2 = st.columns(2)
            with col1:
                groomer = st.selectbox("Select Groomer", GROOMERS, key="groomer")
                date = st.date_input("Select Date", min_value=datetime.date.today(), key="booking_date")
                date_str = date.strftime("%Y-%m-%d")
                booked = get_booked_slots(date_str)
                available_slots = [slot for slot in TIME_SLOTS if slot not in booked]
                time_slot = st.selectbox("Select Time Slot", available_slots, key="time_slot")
            with col2:
                pet_type = st.selectbox("Pet Type", PET_TYPES, key="pet_type")
                weight_range = st.selectbox(
                    "Weight Range",
                    [row["range"] for row in (DOG_PRICES if pet_type == "Dog" else CAT_PRICES)],
                    key="weight_range"
                )
                if pet_type == "Cat":
                    coat_type = st.radio("Coat Type", ["Short", "Long"], key="coat_type", horizontal=True)
                else:
                    coat_type = "short"
                package = st.selectbox("Package", list(PACKAGES.keys()), key="package")

            st.markdown("#### Bundle Add-ons (must be selected with a package)")
            selected_bundles = []
            cols = st.columns(4)
            for idx, addon in enumerate(BUNDLE_ADDONS):
                with cols[idx % 4]:
                    checked = st.checkbox(f"{addon['name']} (+${addon['price']})", key=f"bundle_{addon['id']}")
                    if checked:
                        selected_bundles.append(addon['id'])

            st.markdown("#### Standalone Add-ons (can be booked alone)")
            selected_standalone = []
            cols = st.columns(4)
            for idx, addon in enumerate(STANDALONE_ADDONS):
                with cols[idx % 4]:
                    checked = st.checkbox(f"{addon['name']} (+${addon['price']})", key=f"stand_{addon['id']}")
                    if checked:
                        selected_standalone.append(addon['id'])

            package_key = PACKAGES[package]
            total = calculate_total(pet_type, weight_range, package_key, coat_type, selected_bundles, selected_standalone)
            st.metric("Estimated Total", f"${total}")

            if st.button("Next → Pet Details"):
                st.session_state.groomer = groomer
                st.session_state.date = date_str
                st.session_state.time_slot = time_slot
                st.session_state.pet_type = pet_type
                st.session_state.weight_range = weight_range
                st.session_state.coat_type = coat_type
                st.session_state.package = package
                st.session_state.selected_bundles = selected_bundles
                st.session_state.selected_standalone = selected_standalone
                st.session_state.total = total
                st.session_state.booking_step = 3
                st.experimental_rerun()

        elif st.session_state.booking_step == 3:
            st.subheader("Step 3: Pet Information")
            col1, col2 = st.columns(2)
            with col1:
                pet_name = st.text_input("Pet Name", key="pet_name")
                breed_options = DOG_BREEDS if st.session_state.pet_type == "Dog" else CAT_BREEDS
                breed = st.selectbox("Breed", breed_options, key="breed")
            with col2:
                age = st.number_input("Age (years)", min_value=0.0, step=0.5, key="age")
                notes = st.text_area("Special Notes (e.g., medical conditions, behaviour)", key="notes")

            st.markdown("### Review & Confirm")
            st.write(f"**Pet**: {pet_name} ({st.session_state.pet_type})")
            st.write(f"**Breed**: {breed}, **Age**: {age} years")
            st.write(f"**Service**: {st.session_state.package}")
            st.write(f"**Groomer**: {st.session_state.groomer}")
            st.write(f"**Date**: {st.session_state.date} at {st.session_state.time_slot}")
            st.write(f"**Total**: ${st.session_state.total}")

            if st.button("Confirm Booking"):
                booking_data = {
                    "phone": st.session_state.phone,
                    "groomer": st.session_state.groomer,
                    "date": st.session_state.date,
                    "time": st.session_state.time_slot,
                    "pet_type": st.session_state.pet_type,
                    "weight_range": st.session_state.weight_range,
                    "coat_type": st.session_state.coat_type,
                    "package": st.session_state.package,
                    "bundles": st.session_state.selected_bundles,
                    "standalones": st.session_state.selected_standalone,
                    "total": st.session_state.total,
                    "pet_name": pet_name,
                    "breed": breed,
                    "age": age,
                    "notes": notes,
                    "timestamp": datetime.datetime.now().isoformat(),
                }
                booking_id = save_booking(booking_data)
                if booking_id:
                    st.session_state.booking_step = 4
                    st.experimental_rerun()

        elif st.session_state.booking_step == 4:
            st.success("🎉 Booking confirmed! We'll send you an SMS reminder.")
            st.balloons()
            st.markdown("""
            **What to expect:**
            - Please arrive 10 minutes early.
            - Bring your pet's vaccination records.
            - Cancellation policy: 50% charge for no-shows without prior notice.
            """)
            if st.button("Book Another"):
                for key in list(st.session_state.keys()):
                    del st.session_state[key]
                st.experimental_rerun()

        # 警告框 + 须知
        st.markdown("---")
        st.markdown("""
        <div class="warning-box">
            <strong>⚠️ Important Notice</strong>
            <ul>
                <li><strong>Severe matted fur</strong> will require extra labour time. Additional surcharges will apply on-site and cannot be calculated via online pricing.</li>
                <li><strong>No-show Rule:</strong> A 50% surcharge of total service value will be charged for unclaimed online bookings without advance cancellation notice. This rule does <strong>NOT</strong> apply to walk-in customers who leave without service.</li>
            </ul>
        </div>
        <div class="info-box">
            <strong>📋 Booking Guidelines</strong>
            <ul>
                <li>Vaccination required for all pets – online and walk-in.</li>
                <li>One pet per booking. Multiple pets? Please book separately.</li>
                <li>All services are offered in 30-min or 60-min fixed slots only.</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

def page_retail():
    with st.container():
        st.markdown('<div class="light-theme">', unsafe_allow_html=True)
        st.markdown("## Explore Our Premium In-Store Pet Supplies")
        st.markdown("at Paw Care Pet Studio")
        st.markdown("---")

        dog_products = [
            {"name": "Premium Dry Kibble", "spec": "5kg bag", "price": "$45", "rating": 4.8, "stock": True},
            {"name": "Natural Treats Mix", "spec": "200g pouch", "price": "$12", "rating": 4.9, "stock": True},
            {"name": "Nylon Lead & Collar Set", "spec": "Adjustable, medium", "price": "$28", "rating": 4.6, "stock": True},
            {"name": "Cozy Fleece Dog Bed", "spec": "Large, machine washable", "price": "$89", "rating": 4.7, "stock": False},
            {"name": "Durable Chew Toys (3pk)", "spec": "BPA-free", "price": "$18", "rating": 4.5, "stock": True},
            {"name": "Grain-Free Wet Food", "spec": "12 cans", "price": "$34", "rating": 4.8, "stock": True},
        ]
        cat_products = [
            {"name": "Indoor Cat Kibble", "spec": "3kg bag", "price": "$39", "rating": 4.7, "stock": True},
            {"name": "Tuna & Chicken Pouch", "spec": "24 x 85g", "price": "$28", "rating": 4.9, "stock": True},
            {"name": "Clumping Cat Litter", "spec": "10kg", "price": "$22", "rating": 4.6, "stock": True},
            {"name": "Scratching Post (Cardboard)", "spec": "Recycled", "price": "$15", "rating": 4.3, "stock": False},
            {"name": "Plush Cat Cave Bed", "spec": "Faux fur, medium", "price": "$65", "rating": 4.8, "stock": True},
            {"name": "Interactive Feather Wand", "spec": "With bell", "price": "$10", "rating": 4.4, "stock": True},
        ]

        tab1, tab2 = st.tabs(["🐶 Dog Products", "🐱 Cat Products"])

        def render_product_grid(products):
            cols = st.columns(3)
            for idx, product in enumerate(products):
                with cols[idx % 3]:
                    stock_label = "✅ Available" if product["stock"] else "❌ Not Available"
                    st.markdown(f"""
                    <div class="card-white">
                        <div style="background:#f0ece6; border-radius:8px; padding:1rem; text-align:center;">
                            <span style="font-size:2rem;">📦</span>
                        </div>
                        <h4>{product['name']}</h4>
                        <p><small>{product['spec']}</small></p>
                        <p><strong>{product['price']}</strong> ⭐ {product['rating']}</p>
                        <p style="color:{'#28a745' if product['stock'] else '#dc3545'}; font-weight:600;">{stock_label}</p>
                        <p style="font-size:0.8rem; color:#888;">🛍️ Available in-store only</p>
                    </div>
                    """, unsafe_allow_html=True)

        with tab1:
            render_product_grid(dog_products)
        with tab2:
            render_product_grid(cat_products)

        st.markdown("---")
        st.markdown("*We display our full range of pet goods online for reference only. All transactions take place in our physical studio.*")
        st.markdown('</div>', unsafe_allow_html=True)

def page_contact():
    with st.container():
        st.markdown('<div class="dark-theme">', unsafe_allow_html=True)
        st.markdown("## Get in Touch")
        st.markdown("Visit us, call, or send a message — we'd love to hear from you.")
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("""
            **📍 Address**
            128 Park St, Liverpool NSW 2170, Sydney Australia

            **🕒 Opening Hours**
            Monday – Saturday 9:00 – 18:00
            Closed Sunday

            **📞 Phone**
            +61 2 9600 8899

            **✉️ Email**
            info@pawcarepetstudio.com
            """)
            st.image("https://via.placeholder.com/400x200/2a1f18/915D38?text=Map+Placeholder", use_column_width=True)
        with col2:
            st.markdown("### Send a Message")
            with st.form("contact_form"):
                name = st.text_input("Your Name")
                email = st.text_input("Your Email")
                message = st.text_area("Message")
                submitted = st.form_submit_button("Send")
                if submitted:
                    st.success("Thank you! We'll get back to you soon.")
        st.markdown('</div>', unsafe_allow_html=True)

# -------------------------------
# 7. 主程序
# -------------------------------
def main():
    st.sidebar.image("https://via.placeholder.com/150x60/1A1A1A/D48F48?text=Paw+Care", use_column_width=True)
    st.sidebar.markdown("## Menu")
    page = st.sidebar.radio(
        "Go to",
        ["Home", "About Us", "Services", "Retail", "Contact"],
        index=0,
        key="page_selector"
    )
    if st.sidebar.button("📅 Book Now", use_container_width=True):
        st.session_state.page = "Services"
        st.experimental_rerun()

    if page == "Home":
        page_home()
    elif page == "About Us":
        page_about()
    elif page == "Services":
        page_services()
    elif page == "Retail":
        page_retail()
    elif page == "Contact":
        page_contact()

    st.sidebar.markdown("---")
    st.sidebar.caption("© 2026 Paw Care Pet Studio. All Rights Reserved.")

if __name__ == "__main__":
    main()